### ISSUE TITLE
This library is little hard to use ...

### ISSUE THREAD

**Issue by qwerty258** [rpicopter/ArduinoMotionSensorExample#16]
The example code works fine on Mega2560, but it won't work when integrated in my own code.

At first I was lured into debug `mpu_init()` because it always return error code until the return value in example is printed out.

Then I found that the calling order of `dmp_enable_feature()` and `mpu_set_dmp_state()` in example may be wrong because when I made the `mpu_set_dmp_state()` last call in `mympu_open ()` it worked.

The big question is why the example works fine ...

**Comment by gregd72002** [comment]
Are you sure you have not hit any memory/heap limit? The solution is not
very streamlined so might need a lot of resources

**Comment by caspian-yez** [comment]
The solution for now is give raw data from register to Raspberry Pi to calculate orientation.
Thank you for reply.
